version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 web: # name of the first service
  build: ui/web # specify the directory of the Dockerfile
  ports:
  - "3000:3000" # specify port mapping
 
 api: # name of the second service
  build: api/sequelize # specify the directory of the Dockerfile
  ports:
  - "8080:8080" #specify ports mapping
  links:
  - database # link this service to the database service
 
 database: # name of the third service
  image: mysql # specify image to build container from
  ports:
  - "3306:3306" # specify port forwarding